title: CS 51B Class Page
description: Class website for CS 51B
theme: just-the-docs

url: https://kevinwang27.github.io/cs51b-site

favicon_ico: "/assets/favicon.ico"

callouts:
  warning:
    title: Warning
    color: red